version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgres/data    

  api:
      build: .
      container_name: "rest-api"
      environment:
          DB_USERNAME: ${POSTGRES_USER}
          DB_PASSWORD: ${POSTGRES_PASSWORD}
          DB_DB: ${POSTGRES_DB}
          DB_HOST: "db"
          DB_TABLE: "postgres"
          DB_PORT: "5432"
      ports :
        - "8080:8080"
      depends_on:
        - db 
      networks:
        - fullstack  
volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
